require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/user_project_roles", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # UserProjectRole. As you add validations to UserProjectRole, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      UserProjectRole.create! valid_attributes
      get user_project_roles_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user_project_role = UserProjectRole.create! valid_attributes
      get user_project_role_url(user_project_role)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_user_project_role_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      user_project_role = UserProjectRole.create! valid_attributes
      get edit_user_project_role_url(user_project_role)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new UserProjectRole" do
        expect {
          post user_project_roles_url, params: { user_project_role: valid_attributes }
        }.to change(UserProjectRole, :count).by(1)
      end

      it "redirects to the created user_project_role" do
        post user_project_roles_url, params: { user_project_role: valid_attributes }
        expect(response).to redirect_to(user_project_role_url(UserProjectRole.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new UserProjectRole" do
        expect {
          post user_project_roles_url, params: { user_project_role: invalid_attributes }
        }.to change(UserProjectRole, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post user_project_roles_url, params: { user_project_role: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested user_project_role" do
        user_project_role = UserProjectRole.create! valid_attributes
        patch user_project_role_url(user_project_role), params: { user_project_role: new_attributes }
        user_project_role.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the user_project_role" do
        user_project_role = UserProjectRole.create! valid_attributes
        patch user_project_role_url(user_project_role), params: { user_project_role: new_attributes }
        user_project_role.reload
        expect(response).to redirect_to(user_project_role_url(user_project_role))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        user_project_role = UserProjectRole.create! valid_attributes
        patch user_project_role_url(user_project_role), params: { user_project_role: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested user_project_role" do
      user_project_role = UserProjectRole.create! valid_attributes
      expect {
        delete user_project_role_url(user_project_role)
      }.to change(UserProjectRole, :count).by(-1)
    end

    it "redirects to the user_project_roles list" do
      user_project_role = UserProjectRole.create! valid_attributes
      delete user_project_role_url(user_project_role)
      expect(response).to redirect_to(user_project_roles_url)
    end
  end
end
